name = "UniversalLogger"
uuid = "5c5e3362-9445-4819-9f95-51c44c51adeb"
authors = ["Colin Summers", "The Contributors of UniversalLogger"]
version = "0.1.0"

[deps]
PushVectors = "36b54c61-190e-5a5f-82d5-6f0a962d7362"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.3"

[targets]
test = ["Test"]
